apiVersion: v1
kind: Namespace
metadata:
  name: redmine
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redmine
  namespace: redmine
  annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::038855800565:role/eksctl-cloudgeeksca-eks-addon-iamserviceacco-Role1-1N62NI9GZ6Q4I  #ARN OF THE ROLE ATTACHED WITH NODE
