---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: redmine
spec:
  provider: aws
  secretObjects:
    - secretName: redmine-creds                          # Match
      type: Opaque
      data:
        - objectName: redmine-creds                       # Match
          key: REDMINE_RDS_CRDS                   # use this a KEY
  parameters:
    objects: |
      - objectName: redmine-rds-creds             # Actual Name of the Secret in Aws SecretManager
        objectType: secretsmanager
        objectAlias: redmine-creds                        # Match
